### ISSUE TITLE
Bench Keccak Cost

### ISSUE THREAD

**Issue by ChihChengLiang** [appliedzkp/zkevm-circuits#168]
### Problem

Try answering these questions

- What's the cost of keccak for 2 inputs? We'll use this one heavily
- How does the cost vary for the different numbers of inputs?
- What's the max number of inputs we can do?
- What's the max number of hashes we can do?

### Solution

Tools available

- https://zcash.github.io/halo2/user/dev-tools.html?highlight=cost%20estimat#cost-estimator
- bench for kzg https://github.com/kilic/halo2/blob/kzg/benches/plonk.rs
- https://hackmd.io/2Fg8SREJSTG3rymPqixogg?view#Cost-analysis

**Comment by CPerezz** [comment]
I think this can be closed via https://github.com/appliedzkp/zkevm-circuits/pull/268. 
Since benchmarks were checked in the branch: https://github.com/appliedzkp/zkevm-circuits/blob/keccak_bench_test/circuit-benchmarks/src/keccak_permutation.rs with the new halo2 version and will also land within the CI in #341 

WDYT @ChihChengLiang ?

**Comment by CPerezz** [comment]
Or do we want to have this issue for the entire keccak circuit? Padding included.

**Comment by ChihChengLiang** [comment]
Yeah, closing sounds good.
