### ISSUE TITLE
bus-mapping: Implement a key-value database for state and storage

### ISSUE THREAD

**Issue by ed255** [appliedzkp/zkevm-circuits#184]
To generate some of the circuit inputs, the bus-mapping needs to be able to query the Ethereum State and Accounts Storage.  For example, following https://github.com/appliedzkp/zkevm-circuits/pull/183:
> The two incomplete error detections are for
ErrContractAddressCollision and ErrInsufficientBalance. Detecting
these errors requires keeping track of the state, which we don't do yet.

For ContractAddressCollision we need to query if an Address exists in the State.
For InsufficientBalance we need to query the Address balance.

So the idea is to have a "PartialState" (state kvdb) type that allows:
- given `address`, read/write `account {nonce, balance, codeHash}`
- given `address, key`, read/write `value`

The bus-mapping should do the following steps:
1. Iterate over all steps and figure out all the State (reads?) and writes
2. Query geth to get the state values for the keys gathered from the previous step (via `eth_getProof`)
3. Fill the state kvdb with that information
4. Process each ExecutionStep, updating the state kvdb accordingly, and querying it when necessary
    - In a revert / error situation, also revert the updates in the state kvdb

**Comment by lispc** [comment]
hi @ed255 , it seems there is another method to handle this problem.    Instead of fetching state/proof from a live archive geth node, is it possible to customize [the tracer used in EVM](https://github.com/appliedzkp/zkevm-circuits/blob/eca224d8b9c531537ac9ccadbfa059cb253cab54/geth-utils/gethutil/trace.go#L87) so the tracer can capture state/proof, then a simple getBlockByNum call get all the needed data without calling getProof many times later?
