### ISSUE TITLE
Replace `assert!` with `debug_assert!` of constraint limitation

### ISSUE THREAD

**Issue by han0110** [appliedzkp/zkevm-circuits#288]
Regard to https://github.com/appliedzkp/zkevm-circuits/pull/279#discussion_r786611406, currently there are many `assert!` in constraint construction gadgets/functions, but it's better to have `debug_assert!` for us to easily identify it's happening in constraint construction time.

**Comment by CPerezz** [comment]
If we implement `debug_assert!` I suggest to add a `debug` profile in `Cargo.toml` which uses `opt-lvl=2 or 3`. So on that way we get a performance similar to the `release` profile but with debug symbols and similar stuff enabled still.

Otherways, since everyone runs tests with `release` profile, no `debug_assertions` will be checked.

**Comment by silathdiir** [comment]
I will work on it. Thanks.
