### ISSUE TITLE
Error message printed in Circuit input builder tests

### ISSUE THREAD

**Issue by ChihChengLiang** [appliedzkp/zkevm-circuits#332]
### Problem

Some error message starts with `trace stopped ...` in the CI run. Although the message indicates some error, the tests still pass

https://github.com/appliedzkp/zkevm-circuits/runs/5182916972?check_suite_focus=true#step:6:681
```
trace stopped unexpectedly, err: execution reverted
test circuit_input_builder::tracer_tests::tracer_err_execution_reverted ... ok
trace stopped unexpectedly, err: gas uint64 overflow
test circuit_input_builder::tracer_tests::tracer_err_gas_uint_overflow ... ok
test circuit_input_builder::tracer_tests::tracer_err_insufficient_balance ... ok
test circuit_input_builder::tracer_tests::tracer_err_invalid_code ... ok
trace stopped unexpectedly, err: invalid jump destination
test circuit_input_builder::tracer_tests::tracer_err_invalid_jump ... ok
trace stopped unexpectedly, err: invalid opcode: opcode 0xf not defined
test circuit_input_builder::tracer_tests::tracer_err_invalid_opcode ... ok
test circuit_input_builder::tracer_tests::tracer_err_max_code_size_exceeded ... ok
trace stopped unexpectedly, err: out of gas
test circuit_input_builder::tracer_tests::tracer_err_out_of_gas ... ok
trace stopped unexpectedly, err: return data out of bounds
test circuit_input_builder::tracer_tests::tracer_err_return_data_out_of_bounds ... ok
test circuit_input_builder::tracer_tests::tracer_err_depth ... ok
trace stopped unexpectedly, err: stack underflow (0 <=> 6)
test circuit_input_builder::tracer_tests::tracer_err_stack_underflow ... ok
trace stopped unexpectedly, err: stack limit reached 1024 (1023)
```

### Solution

Need investigation

cc @ed255

**Comment by ed255** [comment]
This issue should be resolved in https://github.com/appliedzkp/zkevm-circuits/pull/292

I think the reason for these messages is twofold:
- 1. Previously the external tracer (written in go) was not propagating the errors to rust, and just printing them to stdout:
https://github.com/appliedzkp/zkevm-circuits/blob/9990b567e1e91b6781b63fb790d46d76b3c4a013/geth-utils/lib/lib.go#L32-L35
- 2. Previously the external tracer was doing a call manually to generate the trace, so if the call returned an error, this was propagated as a tracer error and printed to stdout:
https://github.com/appliedzkp/zkevm-circuits/blob/9990b567e1e91b6781b63fb790d46d76b3c4a013/geth-utils/gethutil/trace.go#L94-L100

In #292 both issues are resolved:
- 1. By returning a string to rust with the error, so that from Rust we can generate an error
- 2. By executing a transaction instead of doing a call manually in the tracer, so that a failed call doesn't result in a tracer error.

In particular these call errors were expected because we are testing EVM error situations, but they shouldn't be tracing errors.

**Comment by ChihChengLiang** [comment]
Thank you Edu, that explains it! I linked this issue to #292 so that it can close this.
