### ISSUE TITLE
circuit-benchmarks stack overflow

### ISSUE THREAD

**Issue by Lawliet-Chan** [appliedzkp/zkevm-circuits#366]
` evm_circuit::evm_circ_benches::bench_evm_circuit_prover`   tests failed: stack overflow.
```
$ cargo test --features benches
running 3 tests
test keccak_permutation::tests::bench_keccak_round ... FAILED

test state_circuit::tests::bench_state_circuit_prover ... ok
test evm_circuit::evm_circ_benches::bench_evm_circuit_prover has been running for over 60 seconds

thread 'evm_circuit::evm_circ_benches::bench_evm_circuit_prover' has overflowed its stack
fatal runtime error: stack overflow
error: test failed, to rerun pass '--lib'
```
Is it a `halo2` bug?

**Comment by HAOYUatHZ** [comment]
Is it because using a too small degree (11)?

In https://github.com/appliedzkp/zkevm-circuits/pull/352 we are using degree=19, and the CI passes.

Difficult to test because 19 is too big for my local laptop....

**Comment by barryWhiteHat** [comment]
If you apply the "benchmark" lable to PRs the CI will run the bench for you. Hopefully with some prover optimizations we can reduce the prover time on laptop.

**Comment by CPerezz** [comment]
Hi @Lawliet-Chan 

Currently, we run the benchmarks by default with a config that "simulates" real word cases of witness input sizes.
This means that the DEGREE we test for is something between 18-24.

This causes the need of aprox 800GB of RAM. Which basically makes any desktop computer to kill the process.

If you want to bench this locally, please use a smaller degree (11-14 should be fine). And also, please check the `README.md` [here](https://github.com/appliedzkp/zkevm-circuits#running-benchmarks) so that you use `make` instead of `cargo directly`. This will help to setup the benches correctly and accomodate the DEGREE of the circuit for the benchmarking better.

Secondly, you can check the results of previous benches that have been run by checking PR's that have the `benchmark` label. In the logs you should be able to see the results :smile:

**Comment by HAOYUatHZ** [comment]
We find that it's because we didn't use `--profile bench`

In `[profile.bench]` we set `overflow-checks = false`.  I turn it into `true` and re-run `DEGREE=11 make evm_bench` then it also fails with `thread 'evm_circuit::evm_circ_benches::bench_evm_circuit_prover' has overflowed its stack`. 
With `false` it passes.

Just wondering will skip `overflow-checks` be a problem?

**Comment by CPerezz** [comment]
So why I recomend to use `make` is because the profile for bench removes a lot of debugging data from the final compiled binary.

In other words, you're processing a lot of debug/dummy info which accomulates in the stack and causes issues. Same will happen with `debug-symbols` probably.

I recommend to stick to the provided config. As anything that is run under `debug` or basic `release` profiles is not guaranteed to be possible to run for benchmarking purposes.


As for the  `overflow_checks`,  we test with them enabled. But benchmarks are done with them deactivated. So we should not be worried.

Closing this. Ping for any concerns and I'll re-open! :)

**Comment by HAOYUatHZ** [comment]
I understand that "unit-test" and "integration-test" are done with `overflow_checks` and pass.

But benching with `overflow_checks=true` will actually fail. My concern is, could benching with `overflow_checks=false` result still be considered accurate? (Though benching with `overflow_checks=true` result doesn't look accurate either.)

**Comment by CPerezz** [comment]
The point is not that the result is not accurate but that the stack explodes. It's not that the software does not it's job.

We can further check this. But since in the tests we don't have any over/underflows and, the benchmarks use the same circuits as the tests, I don't see why it should be an issue.

Could you clarify where exactly do you see the issue here @HAOYUatHZ as I'm afraid I'm not completely following you or missing something :)

**Comment by CPerezz** [comment]
Glad we agreed! 

Happy to answer any further questions you might have.
