### ISSUE TITLE
`benchmark` label only runs EVMCircuit benchmarks but not StateCircuit ones

### ISSUE THREAD

**Issue by CPerezz** [appliedzkp/zkevm-circuits#368]
As can be seen in #352 logs, no reports about `State` circuit were found anywhere. IIUC, they were not run. 

I think this is not the expected behaviour, and that the `benchmark` label should run them all.

cc: @AronisAt79

**Comment by HAOYUatHZ** [comment]
because in https://github.com/appliedzkp/zkevm-circuits/blob/main/.github/proverCiScripts/execBench.sh#L15 (invoked by https://github.com/appliedzkp/zkevm-circuits/blob/main/.github/workflows/gh-actions-prover-benches.yml)

we only run `bench_evm_circuit_prover `

uf we want to bench on `StateCircuit`, we need `bench_state_circuit_prover` (https://github.com/appliedzkp/zkevm-circuits/blob/main/circuit-benchmarks/src/state_circuit.rs#L24) as well

**Comment by CPerezz** [comment]
@HAOYUatHZ yep. I agree. We should ammend this @AronisAt79 and add the State and probably the keccak benches to that script.

**Comment by AronisAt79** [comment]
Thanks @CPerezz and @HAOYUatHZ , please see my comments on issue #371 
cc: @HAOYUatHZ , @CPerezz

**Comment by CPerezz** [comment]
Closed via #371
