### ISSUE TITLE
Silent Result->Option fails

### ISSUE THREAD

**Issue by adria0** [appliedzkp/zkevm-circuits#407]
In the code there are some `Result` converted into `Option` via `.ok()`, so, there was no checking on this.  When fixing them https://github.com/adria0/zkevm-circuits/commit/a4fe6d93ef1d129ac5e9da2ca525f1c147b9ae94, the tests on the bytecode circuit  fails. Halo2 says that is a low k problem, but when I bump the k (even till 20) the problem still persists.

Contacted with @Brechtpd, created https://github.com/zcash/halo2/issues/533

cc/ @therealyingtong

**Comment by therealyingtong** [comment]
I believe this is a bug in the `bytecode_unroller` code. I think this line should say `offset..last_row_offset` instead of `offset..size`.

https://github.com/appliedzkp/zkevm-circuits/blob/1ec38f207f150733a90081d3825b4de9c3a0a724/zkevm-circuits/src/bytecode_circuit/bytecode_unroller.rs#L367

**Comment by adria0** [comment]
@therealyingtong, with this change tests does not fail with `low k` but verify fails for other cases:
for the simple unrolling test 

```
---- bytecode_circuit::bytecode_unroller::tests::bytecode_unrolling stdout ----
[zkevm-circuits/src/bytecode_circuit/bytecode_unroller.rs:316] self.minimum_rows = 8
[zkevm-circuits/src/bytecode_circuit/bytecode_unroller.rs:317] last_row_offset = 1017
Region 2 ('assign bytecode') uses Gate 0 ('is_zero gate'), which requires cell in column Column { index: 4, column_type: Advice } at offset 1023 to be assigned.
Region 2 ('assign bytecode') uses Gate 1 ('continue'), which requires cell in column Column { index: 1, column_type: Advice } at offset 1023 to be assigned.
Region 2 ('assign bytecode') uses Gate 1 ('continue'), which requires cell in column Column { index: 5, column_type: Advice } at offset 1023 to be assigned.
Region 2 ('assign bytecode') uses Gate 1 ('continue'), which requires cell in column Column { index: 0, column_type: Advice } at offset 1023 to be assigned.
Region 2 ('assign bytecode') uses Gate 1 ('continue'), which requires cell in column Column { index: 6, column_type: Advice } at offset 1023 to be assigned.
Region 2 ('assign bytecode') uses Gate 1 ('continue'), which requires cell in column Column { index: 9, column_type: Advice } at offset 1023 to be assigned.
Region 2 ('assign bytecode') uses Gate 1 ('continue'), which requires cell in column Column { index: 8, column_type: Advice } at offset 1023 to be assigned.
Region 2 ('assign bytecode') uses Gate 2 ('start'), which requires cell in column Column { index: 8, column_type: Advice } at offset 1023 to be assigned.
Region 2 ('assign bytecode') uses Gate 4 ('always'), which requires cell in column Column { index: 4, column_type: Advice } at offset 1023 to be assigned.
Region 2 ('assign bytecode') uses Gate 5 ('padding'), which requires cell in column Column { index: 9, column_type: Advice } at offset 1023 to be assigned.
```
I also see that the  `minimum_rows` (that comes from `ConstraintSystem`) is only used in the bytecode_unroller and nowhere else, so at this moment is not clear for me how this parameter should be used.

**Comment by Brechtpd** [comment]
The problem is that halo2 requires all cells to be assigned for a gate that uses an enabled selector. And cells on unusable rows are not assignable (normally). By chance this wasn't a problem with the previous error handling because of how the layouter works in halo2
- The first phase is only used to get the dimensions of the region, which allows all cells to be assigned (even unusable ones)
- The second phase is actually used for assigning value, which does have the unusable rows check.

Because all rows were assigned until an error was thrown, which in the first phase were actually all rows, all cells (even the unusable ones that normally can't be assigned) were actually seen as assigned by the mock prover and so all checks passed successfully. The new code does not assign these unusable cells anymore in the first phase, and so now we get these unassigned cell errors for unusable rows. The reason is because gates like `q_enabled * (1 - q_first) * meta.query_advice(column, Rotation::prev())` are used, which halo2 currently actually doesn't allow (because the gate uses an enabled selector, but on the first row the gate references a cell on the previous row which is on an unusable row, but of course the gate also disables the use of this cell on the first row). I don't see a reason why this would be an invalid gate (similar checks are done for lookup/permutation arguments), but of course I could be wrong.

There's actually a very easy way to work around this halo2 check: use a fixed column instead of a selector for `q_enable` so the MockProver doesn't do this "all cells in a gate need to be assigned when a selector is enabled" check. However, I would find it very strange if this is allowed but using selectors is not allowed, so I hope https://github.com/zcash/halo2/issues/533 can shine some light on this.

Also, https://github.com/appliedzkp/zkevm-specs/issues/151 already changes how the bytecode circuit would work a bit and that doesn't use previous rows so kind of already works around this potential halo2 issue.
